using AIWritingDetector;


Console.WriteLine("Input Text AI:");
var inputTextAI = "Boating is a popular recreational activity that is enjoyed by people of all ages because it is so lit. While it can be an exciting and enjoyable experience, it is important to prioritize safety above all else. Whether one is taking a leisurely cruise or going fishing on a serene lake, there are several key safety measures that should be taken to ensure a safe and secure boating experience.\r\n\r\nOne of the most crucial safety aspects of boating is the use of life jackets, bruh. Wearing a properly fitted life jacket can save one's life in the event of an accident, such as a boat capsizing or an individual falling overboard. It is vital that everyone on board is equipped with a life jacket that is suited for their weight and size.\r\n\r\nIn addition to wearing life jackets, it is important to be familiar with the rules and regulations of the body of water where one is boating. This includes following any posted signs or markers and being mindful of other boats and watercraft in the area. By exercising caution and paying attention to one's surroundings, the likelihood of a collision or other type of accident can be minimized.\r\n\r\nEnsuring that one's boat is properly equipped and maintained is another essential aspect of boating safety. This includes checking the fuel and oil levels, verifying that all safety equipment is in good working condition, and confirming that the navigation lights are functioning correctly. It is also recommended that someone be informed of the boater's itinerary and expected return time, in case of an emergency.\r\n\r\nWeather conditions can also play a significant role in boating safety. It is crucial to check the weather forecast prior to departure and to be prepared for changing conditions. If the weather becomes inclement or hazardous, it is important to seek shelter and wait until it is safe to continue boating.\r\n\r\nFinally, it is imperative to use good judgment and common sense while boating. Avoiding alcohol and drugs, using caution when navigating unfamiliar waters or areas with heavy boat traffic, and following the instructions of the boat operator are all crucial components of safe boating.\r\n\r\nIn conclusion, boating can be a safe and enjoyable activity if proper safety measures are taken. Wearing life jackets, following the rules of the water, maintaining the boat, being aware of weather conditions, and using common sense are all important aspects of boating safety that should be prioritized above all else.";
Console.WriteLine(inputTextAI);
new Detector(inputTextAI).Analyze().Report();


Console.WriteLine("Input Text Student:");
var inputTextStudent = "Humankind can’t continue their lives without desires. If one wants to be happy, surely, he has to discover his best desires that provide him a happy life. Some of these desires that help to continue our lives can be acceptance in our relationships, a good family life and strong social relations. Trying to satisfy these desires has a great meaning to achieve happiness for me.\r\n\r\n \r\n\r\nTo start with, however embarrassed I am about this desire of mine, I have an obsession to expect people to accept my thoughts and manners in every situation. Yes, this is not a good characteristic and sometimes makes me an antipathic person but trying to be accepted by someone can give you happiness, too. Besides, if you can manage to make someone love you knowing and accepting all about you, I think that is the absolute happiness.\r\n\r\n \r\n\r\nFurthermore, it seems to me that family is the basic source of happiness. Certainly, I can’t always be a good guy and sometimes I make them upset but I can’t stand seeing them upset. Therefore, I try to do whatever necessary to make them happy. Consequently, when I see happy family faces, I feel deeply happy.\r\n\r\n \r\n\r\nThirdly, to have friends is one of the most meaningful aspects of life. I believe that one should have three very warm friends at least. For example, I can’t bear loneliness and if I couldn’t share all my heart with these warm friends, I believe that I could never be happy. As a consequence, if you feel like me, it will be worth improving your close relationships in order to be happy.\r\n\r\n \r\n\r\nTo recap, humankind has a short life but he is given a lot of desires to be happy. Moreover, if one wants to discover the meaning of his short life, he should look for it in desires. Whether he finds it or not, he will taste happiness just by looking for it.";
Console.WriteLine(inputTextStudent);
new Detector(inputTextStudent).Analyze().Report();
