namespace AIWritingDetector
{
    public static class Words
    {
        public static List<string> Contractions = new List<string> {
            "ain't", "aren't", "can't", "could've", "couldn't", "didn't", "doesn't", "don't",
            "hadn't", "hasn't", "haven't", "he'd", "he'll", "he's", "how'd", "how'll",
            "how's", "I'd", "I'll", "I'm", "I've", "isn't", "it'd", "it'll", "it's", "let's", "ma'am",
            "might've", "mightn't", "must've", "mustn't", "needn't", "o'clock", "oughtn't", "shan't",
            "she'd", "she'll", "she's", "should've", "shouldn't", "somebody's", "someone's", "something's",
            "that'll", "that're", "that's", "there'd", "there'll", "there're", "there's", "they'd", "they'll",
            "they're", "they've", "this's", "those're", "to've", "wasn't", "we'd", "we'll", "we're", "we've",
            "weren't", "what'd", "what'll", "what're", "what's", "what've", "when's", "where'd", "where's",
            "who'd", "who'll", "who's", "who've", "why'd", "why'll", "why's", "won't", "would've", "wouldn't",
            "y'all", "you'd", "you'll", "you're", "you've"
        };

        public static List<string> SlangWords = new List<string>()
        {
            "bruh", "ace", "aight", "amigo", "back in the day", "baller", "bangin'", "beat", "beemer", "benjamins",
            "bling", "boogie", "boss", "bro", "bubble", "buck", "bucks", "buddy", "bummed", "busted", "c-note",
            "chill", "chillin'", "chump", "clueless", "cool", "cop", "crap", "cruisin'", "dawg", "dibs",
            "dime", "dope", "down with", "dude", "dumb", "face", "fa sho", "fitty", "fo' shizzle", "freakin'",
            "freaky", "frontin'", "funky", "gangsta", "gear", "ghetto", "gimme", "gnarly", "grill",
            "grind", "grip", "guap", "hang loose", "hater", "hecka", "high", "holla", "hood", "hook up",
            "hype", "ill", "jam", "janky", "jive", "jonesin'", "kickin'", "kicks", "killer", "kool",
            "leet", "legit", "lucky", "mad", "makin' bacon", "moolah", "munchies", "my bad", "my man", "nasty",
            "neat", "nerd", "nifty", "nose candy", "noob", "off the chain", "off the heezy", "old school", "on the dl",
            "on the reg", "pimpin'", "pix", "posse", "primo", "props", "punk", "put on", "ratchet", "bae", "banger",
            "beef", "blaze", "boi", "bomb",
            "bougie", "clutch", "cray", "crunk", "da bomb", "dank", "fam", "fleek", "fly", "fool", "fresh", "g",
            "goodies", "homie", "hookup", "hottie",
            "jelly", "jock", "kickin' it", "krunk", "lit", "loc", "ninja", "og", "peace out",
            "phat", "pimp", "player", "preppy", "psyched", "ride", "rockin'",
            "rollin'", "salt", "savage", "scrilla", "shady", "shawty", "shizzle", "skank", "sketchy", "slick",
            "snap", "snazzy", "snitch", "solid", "soul", "stackin'", "steezy", "stoked", "straight up", "swag",
            "sweet", "tight", "trill", "wack", "wavy", "weirdo", "whack", "wildin'", "woke", "y'all",
            "bet", "deuces", "drip", "flex", "finesse", "goat", "litty",
            "no cap", "on fleek", "peep", "plug", "salty", "slay", "smh", "squad", "stan",
            "sus", "thicc", "thirsty", "throw shade", "trippin", "vibin", "werk", "woat", "yeet", "yolo", "naw",
            "nerd out", "on point", "pissed",
            "playa", "pop a squat", "pop off", "preach", "pwned", "real talk", "rekt",
            "rip", "scrub", "shake", "shook", "sick", "skrrt", "snatched", "swerve", "tbh",
            "totes", "turnt", "we out", "what's good", "whip", "wig", "ya dig", "yasss", "you trippin'", "zoned",
            "zonked", "zoomies", "cheddar", "clapback", "dead", "faded", "finna", "fire",
             "amped", "bag", "bite", "boonies", "bounce", "brah", "brick",
            "bubba", "cackle", "cap", "chirp",
            "chum", "chunky", "clique", "crib", "crushing it", "cuttin' up", "deadass", "dial", "dinger", "dip",
            "diss", "dolled up", "domestic", "drool-worthy", "dry-snitching", "epic", "extra", "fake news",
            "famished", "fin", "fire up", "fish", "fluff", "foolin'", "fuego", "gassed up", "gig", "glo-up",
            "haul ass", "heat", "hench", "hundo p", "hypebeast", "ice", "jacked", "jawn",
            "jit", "juke", "kicking", "kip", "lame", "lit af", "loud", "lush",
            "mad dogging", "man bun", "melt", "mint", "mood", "my guy", "netflix and chill", "not my circus", "nugget",
            "on blast", "on god", "on my grind", "on the come up", "on the low", "outchea", "outta pocket", "pine",
            "piping hot", "pitch", "post up", "pound sand", "pump fake", "punch it", "pushin'",
            "q", "rag", "rage", "rank", "ride or die", "rinky-dink", "rise and grind", "road beef", "rock with",
            "run it up", "savage af", "schmooze", "shooketh", "shotty", "sipping", "slide", "snack", "sneakerhead", "snooze",
            "so extra", "spill the tea", "stance", "stay woke", "steal", "stoop", "straight fire", "strapped",
            "swerve on", "gonna", "wanna", "kinda", "gotta", "dunno", "y'all", "shoulda",
            "coulda", "woulda", "outta", "lemme", "gimme",
            "gotcha", "whatcha", "could be", "would be", "should be", "oughta", "musta", "mighta", "may have",
            "might have", "could have", "would have", "should have", "ought to have", "must have",
            "lemme know", "outta here", "sorta", "got it", "good idea", "bad idea", "totally", "absolutely", "seriously", "definitely",
            "basically", "actually", "literally", "probably", "possibly", "hopefully", "technically", "realize", "anyways",
            "anyhoo", "oh well", "oh no", "oh yeah", "oh shoot", "oh my gosh", "oh my goodness", "oh my", "like",
            "you know", "whatever", "anyway", "anyhow", "how come", "what's up", "not bad", "pretty", "super",
            "freakin", "totally awesome", "really", "irregardless","conversate",
            "upmost", "supposably", "orientate", "expresso", "nucular", "misunderestimate", "sherbert", "bemuse", "flustrated",
            "chillax", "ginormous", "confuzzled", "inflammable", "hunnerd", "irregardlessly", "yous", "alot",
            "howdy", "yeehaw", "fella", "sis", "cuz", "hella", "dang", "freakin'", "frickin'",
            "shoot", "darn", "dagnabbit", "daggonit", "gosh", "jeez", "dangit", "fiddlesticks", "kind of", "sort of"
        };

        public static List<string> StudentWords = new List<string>
        {
            "Dormitory",
            "Extracurricular",
            "Syllabus",
            "Plagiarism",
            "Lecture",
            "Pedagogy",
            "Thesis",
            "Bibliography",
            "Trigonometry",
            "Rhetoric",
            "Aristotle",
            "Extrapolate",
            "Epistemology",
            "Renaissance",
            "Dichotomy",
            "Linguistics",
            "Hierarchical",
            "Osmosis",
            "Curriculum",
            "Ameliorate",
            "Aberration",
            "Sine qua non",
            "Axiom",
            "Rubric",
            "Conundrum",
            "Enigma",
            "Cacophony",
            "Pensive",
            "Idiosyncrasy",
            "Idiom",
            "Anecdote",
            "Hyperbole",
            "Allusion",
            "Oxymoron",
            "Euphemism",
            "Metaphor",
            "Simile",
            "Personification",
            "Irony",
            "Symbolism",
            "Allegory",
            "Foreshadowing",
            "Imagery",
            "Theme",
            "Plot",
            "Protagonist",
            "Antagonist",
            "Conflict",
            "Resolution",
            "Anthropology",
            "Archeology",
            "Astronomy",
            "Bacteriology",
            "Biochemistry",
            "Biotechnology",
            "Botany",
            "Cardiology",
            "Chemistry",
            "Chiropractic",
            "Climatology",
            "Criminology",
            "Dentistry",
            "Ecology",
            "Economics",
            "Education",
            "Endocrinology",
            "Entomology",
            "Epidemiology",
            "Ethnography",
            "Ethology",
            "Forensic",
            "Gastroenterology",
            "Genealogy",
            "Genetics",
            "Geography",
            "Geology",
            "Geriatrics",
            "Hematology",
            "Histology",
            "Immunology",
            "Linguistics",
            "Meteorology",
            "Microbiology",
            "Mycology",
            "Neurology",
            "Nuclear physics",
            "Nutrition",
            "Obstetrics",
            "Oncology",
            "Ophthalmology",
            "Orthopedics",
            "Paleontology",
            "Pathology",
            "Pharmacology",
            "Physiology",
            "Psychiatry",
            "Radiology",
            "Sociology",
            "Toxicology",
            "Virology",
            "Abolitionist",
            "Adversary",
            "Altruistic",
            "Ameliorate",
            "Anachronistic",
            "Aristocracy",
            "Benevolent",
            "Bourgeoisie",
            "Clandestine",
            "Cognizant",
            "Conundrum",
            "Cordial",
            "Debacle",
            "Demagogue",
            "Dichotomy",
            "Dilemma",
            "Disenfranchise",
            "Disparage",
            "Dogmatic",
            "Egalitarian",
            "Ephemeral",
            "Equivocate",
            "Evanescent",
            "Exacerbate",
            "Facetious",
            "Fastidious",
            "Flummox",
            "Fortitude",
            "Foster",
            "Gregarious",
            "Hegemony",
            "Hypocrisy",
            "Iconoclast",
            "Idiosyncrasy",
            "Impetus",
            "Incongruous",
            "Ineffable",
            "Ingenuous",
            "Inscrutable",
            "Insidious",
            "Interpolate",
            "Intrepid",
            "Intrinsic",
            "Juxtaposition",
            "Kaleidoscope",
            "Languid",
            "Litigious",
            "Ludicrous",
            "Malleable",
            "Misanthrope",
            "Mitigate",
            "Nihilism"
        };

        // Advanced Grammar that might be detectable by Regex.
        // - more smarter
        // - double negatives
        // - improper their : look for "their _ing"
        // - "use to" without can, should, will, must etc. 

        public static List<string> GrammaticalErrors = new List<string>
        {
            "could of", "I seen", "I done", "should of", "They was",
            "laying on the table", "He don't", "She don't",
            "than her", "than him", "feel badly", "Their going",
            "could care less", "laying in bed", "laying in the bed", "laying in his bed", "laying in her bed", "laying in my bed",
            "have came", "I seen", "He seen", "she seen", "they seen",
            "We was", "can't hardly", "is effecting",
            "She is taller than me.", "he and I.", "she and I.", "him and I.", "her and I.", "them and I.", "they and I.",
            "have went", "have wrote",
            "Their going", "Their are",
            "not use to",
            "to close", "to far",
        };
    }
}
